### ISSUE TITLE
Change handling of sub-modules

### ISSUE THREAD

**Issue by webflo** [drupal-composer/drupal-packagist#10]
_From @bforchhammer on November 23, 2014 18:53_

Ideas:
- Leave "provides" statement in `composer.json`
- Move submodule "requirements" into "suggest" section
- Add new `metapackage` entries for each sub module; add in/parse submodule dependencies and other information.

Related discussion:
- https://github.com/winmillwill/drupal-parse-composer/issues/4
- https://github.com/winmillwill/drupal-parse-composer/issues/6
- https://github.com/winmillwill/drupal-parse-composer/issues/8

_Copied from original issue: webflo/packagist#2_

**Comment by webflo** [comment]
Moved submodule "requirements" into "suggest" section in https://github.com/webflo/drupal-parse-composer/tree/submodule-dependencies

Some examples:
- http://drupal-packagist.webflo.io/packages/drupal/ctools
- http://drupal-packagist.webflo.io/packages/drupal/panels

**Comment by mikkeschiren** [comment]
I am all in for this solution - I don't want unknown versions of other modules downloaded because of dependencies. Suggestions provides the information needed.

**Comment by webflo** [comment]
We changed the behaviour a while ago and it works great. Created another issue for metepackages (#15).
