### ISSUE TITLE
drupal-packagist.org

### ISSUE THREAD

**Issue by derhasi** [drupal-composer/drupal-packagist#16]
> The thing is that the drupal-packagist.org domain is just an AWS Route 53 DNS entry that doesn't point anywhere. Only static.drupal-packagist.org actually points at a service, and that's just an S3 bucket. If someone wants to pay for a server to run the packagist fork in this organization, I'm happy to hand over the domain.

The drupal packagist server is currently run by @webflo on Digital Ocean. @winmillwill can you point drupal-packagist.org on that server? Otherwise I could take over the domain if you want, to do that.

**Comment by derhasi** [comment]
Follow up to https://github.com/drupal-composer/drupal-packagist/issues/1

**Comment by kasperg** [comment]
This issue no longer seems relevant since we now have http://packagist.drupal-composer.org/.

**Comment by derhasi** [comment]
Kinda, but it would be nice, if we talk about "Drupal Packagist", we can also refer as drupal-packagist.org being a domain to point at it.

So, @winmillwill, if you find some time, please let us know if you want and can redirect or transfer the domain ;)

**Comment by webflo** [comment]
drupal-packagist.org was free. I have created a redirect to https://packagist.drupal-composer.org.
