### ISSUE TITLE
Merge upstream packagist repository

### ISSUE THREAD

**Issue by webflo** [drupal-composer/drupal-packagist#20]
We should merge the upstream repo regularly. The logic around package providers was improved a few days ago.

**Comment by derhasi** [comment]
I posted a PR, so the Packagist WebBundle can be subtree splitted: https://github.com/composer/packagist/pull/478

With https://github.com/derhasi/packagist-webbundle I prepared a substree split that can be triggered by Travis CI.

**Comment by derhasi** [comment]
@webflo, can you rebase the current master on composer/packagist:master? So we could see what we changed for Drupal Packagist in a linear history. There where to many rebase conflicts, and as I did not write the code, I think it would be best you review that at the first place ;)

After that I could try to add `composer/packagist-webbundle` on my own I guess.

**Comment by webflo** [comment]
Merged and deployed last week.
