### ISSUE TITLE
Some packages don't have version information.

### ISSUE THREAD

**Issue by dutchiexl** [drupal-composer/drupal-packagist#24]
So projects pulled from the packagist are missing the

<pre>
; Information added by Drupal.org packaging script on 2015-01-06
version = "7.x-3.6"
core = "7.x"
project = "context"
datestamp = "1420573188"
</pre>

This makes it impossible to use patches. Is there a solution ?

**Comment by dutchiexl** [comment]
Posted this issue on the parse composer page: https://github.com/drupal-composer/drupal-parse-composer/issues/32

**Comment by webflo** [comment]
Thanks for the bug report. Please follow https://github.com/drupal-composer/drupal-parse-composer/issues/32
