### ISSUE TITLE
drupal/entityqueue requires drupal/system which is not a real package

### ISSUE THREAD

**Issue by davidbarratt** [drupal-composer/drupal-packagist#31]
I just noticed that [drupal/entityqueue](https://packagist.drupal-composer.org/packages/drupal/entityqueue) requires `drupal/system` which is not a real package.

**Comment by webflo** [comment]
Thats correct, but drupal/system is part of drupal/drupal. I think this is not a bug. Currently is it required that you add drupal/drupal to your root composer json.

**Comment by webflo** [comment]
#15 should fix this in the long run.

**Comment by webflo** [comment]
Closed in favour of #15
