### ISSUE TITLE
8.x versions of modules are missing from the registry

### ISSUE THREAD

**Issue by echernyavskiy** [drupal-composer/drupal-packagist#34]
For instance, drush extension "[composer](https://www.drupal.org/project/composer)" - [only the DEV version is available](https://packagist.drupal-composer.org/packages/drupal/composer). [Views](https://packagist.drupal-composer.org/packages/drupal/views) - same story.

**Comment by webflo** [comment]
I look into the problem with composer soon. But i don´t understand the issue with views. Views is in D8 Core. There is not views module in contrib.

**Comment by echernyavskiy** [comment]
Doh, apologies - really just picked the first popular Drupal module that came to mind. [panels](https://packagist.drupal-composer.org/packages/drupal/panels) would be a better example.

**Comment by webflo** [comment]
I found the problems with panels. We D8 version won´t show up because the parser throughs some errors. Becuase zhe panels repo contains a mix of D8 and D7 Modules. panels.info.yml is D8, but the submodule i18n_panels is not D8 compatibility.

http://cgit.drupalcode.org/panels/tree/i18n_panels?h=8.x-3.x

**Comment by echernyavskiy** [comment]
It's really across the board it looks like: [token](https://packagist.drupal-composer.org/packages/drupal/token), [pathauto](https://packagist.drupal-composer.org/packages/drupal/pathauto) etc.

**Comment by webflo** [comment]
Look at the pathauto repo. The module has a d7 info file. It is not a valid d8 module

**Comment by webflo** [comment]
And the token dev release ia available on Drupal packagist ...

**Comment by webflo** [comment]
- Views: No d8 Version, moved to contrib
- Composer: Fixed, https://packagist.drupal-composer.org/packages/drupal/composer
- Panels: Fixed, https://packagist.drupal-composer.org/packages/drupal/panels
- Pathauto: Won´t fix, the repo contains no valid [module].info.yml file
- Token: is already available, https://packagist.drupal-composer.org/packages/drupal/token

**Comment by echernyavskiy** [comment]
@webflo thanks for fixing this!
