### ISSUE TITLE
The HOME or COMPOSER_HOME environment variable must be set

### ISSUE THREAD

**Issue by timmillwood** [drupal-composer/drupal-packagist#35]
Getting the following error when trying to submit a package on https://packagist.drupal-composer.org/packages/submit

`Uncaught Exception: [RuntimeException] The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly`

**Comment by Codenator81** [comment]
How  you solve this problem? I got the same error

**Comment by webflo** [comment]
Drupal Packagist is not designed to submit packages though the UI. Your module should appear automatically. We should disable the login and submit completely.

**Comment by Codenator81** [comment]
My module in sandbox. Any way thanks for response )

**Comment by webflo** [comment]
Sandboxes are not supported atm. Sorry

**Comment by Codenator81** [comment]
No problem I put module on packagist
