### ISSUE TITLE
Newly added package not installing

### ISSUE THREAD

**Issue by albertvolkman** [drupal-composer/drupal-packagist#39]
A newly added module is not installing for some reason. Details below-

Module:
https://www.drupal.org/project/twitter_pane

composer show drupal/twitter_pane output:

```
name     : drupal/twitter_pane
descrip. : Provides a configurable pane for a Twitter widget feed.
keywords :
versions : 7.1.x-dev, dev-7.x-1.x
type     : library
source   : [git] http://git.drupal.org/project/twitter_pane.git d157902b1e6278e1f95e418cba9dcd3862ccc464
dist     : [zip] http://ftp.drupal.org/files/projects/twitter_pane-7.x-1.x-dev.zip
names    : drupal/twitter_pane

requires
drupal/drupal 7.*
drupal/panels 7.*
```

composer update output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package drupal/twitter_pane could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by webflo** [comment]
I did `git clone https://github.com/drupal-composer/drupal-project.git --branch 7.x foo && cd foo && composer require -vvv drupal/twitter_pane:7.1.x-dev` and everything went fine.

**Comment by albertvolkman** [comment]
I had an additional entry for `drupal/twitter_pane`. Sorry to bother.

**Comment by albertvolkman** [comment]
I take that back... the package is going to /vendor instead of the `type: drupal-module` location. Also-

```
$ composer show drupal/twitter_pane
name     : drupal/twitter_pane
descrip. :
keywords :
versions : * master, 7.1.x-dev, dev-7.x-1.x
type     : drupal-module
source   : [git] http://git.drupal.org/sandbox/jaykali/2260089.git master
dist     : []
names    : drupal/twitter_pane
```

For some reason it's showing the (now defunct) sandbox for the source.

**Comment by webflo** [comment]
Something is wrong in your composer.json file. Maybe a custom repository? I suppose git.drupal.org/sandbox/jaykali/2260089.git. The git url in your composer show output should be http://git.drupal.org/project/twitter_pane.git

**Comment by albertvolkman** [comment]
Initial issue was related to cache, and then the module type was set to "library" instead of "drupal-module". Fixed by @webflo. Thanks!!
