### ISSUE TITLE
Old drupal/coder packages

### ISSUE THREAD

**Issue by deviantintegral** [drupal-composer/drupal-packagist#40]
The latest release of Coder is 8.x-2.4. Any idea why it's pulling the older tag in, given that Packagist has a newer version upstream?

https://packagist.org/packages/drupal/coder

```
$ composer require drupal/coder
Using version ^8.2 for drupal/coder
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing squizlabs/php_codesniffer (2.0.0)
    Loading from cache

  - Installing drupal/coder (8.2.0-beta1)
    Loading from cache

Writing lock file
Generating autoload files
```

**Comment by webflo** [comment]
I take a look.

**Comment by webflo** [comment]
Someone had this issue before and asked on Stackoverflow. I posted an workaround. http://stackoverflow.com/questions/29400088/how-do-i-use-a-package-in-composer-that-has-the-same-name-as-another-package

**Comment by webflo** [comment]
Fixed it, coder module is up to date.

**Comment by deviantintegral** [comment]
I was also able to work around this by specifying a higher version requirement. But the above workaround is better because it lets you handle scenarios where two packages have the same name and the same version, but different contents. Thanks @webflo !
