### ISSUE TITLE
userpoints_badges

### ISSUE THREAD

**Issue by albertvolkman** [drupal-composer/drupal-packagist#41]
The userpoints_contrib module contains the userpoints_badges submodule. However, it is now it's own module-

https://www.drupal.org/project/userpoints_badges

and will soon be removed from userpoints_contrib-

https://www.drupal.org/node/2619420

Is there a way to get userpoints_badges removed from userpoints_contrib's "Replaces" section, so that it will install from the correct repo?

**Comment by webflo** [comment]
Hi, the replace key for userpoints_badges will be removed in the next dev release automatically. The replace information depends on the info files in your repository. If the info file is gone, the replace will be gone,

**Comment by webflo** [comment]
Looks ok, right?

https://packagist.drupal-composer.org/packages/drupal/userpoints_contrib
https://packagist.drupal-composer.org/packages/drupal/userpoints_badges

**Comment by albertvolkman** [comment]
Got it. Looks correct, thank you :)
