### ISSUE TITLE
registry_rebuild (and potentially) other projects missing some releases

### ISSUE THREAD

**Issue by echernyavskiy** [drupal-composer/drupal-packagist#42]
Was running a routine `composer update` and noticed that _registry_rebuild_ fails the dependency resolving process as Drupal packagist does not have any information about the latest recommended version of the project that was requested.
[drupal.org](https://www.drupal.org/project/registry_rebuild) says 2.2 is recommended while [packagist](https://packagist.drupal-composer.org/packages/drupal/registry_rebuild) only has up to 1.4.

This has happened before with another project and IIRC the releases parser was at fault at that time.

**Comment by webflo** [comment]
The dependency parsing on drupal packagist does not work in any case. Things are easier with a composer.json in the repo itself. I filled a issue in the registry_rebuild issue queue. 

https://www.drupal.org/node/2622718#comment-10604008

**Comment by echernyavskiy** [comment]
:thumbsup:

Just curious: how does adding composer.json facilitate release info update?

**Comment by webflo** [comment]
We have this info-file parser library (https://github.com/drupal-composer/drupal-parse-composer/blob/master/src/Project.php#L50) and the parser stops if there is no valid info file. Drupal Packagist uses the `composer.json` in favour of the parser.

**Comment by webflo** [comment]
Package is up to date. https://packagist.drupal-composer.org/packages/drupal/registry_rebuild

**Comment by echernyavskiy** [comment]
Gotchya, and appreciate such a quick turnaround.

**Comment by echernyavskiy** [comment]
I just ran `composer update` with registry_rebuild pinned at 2.2 and it succeeded, however `composer install` then installs it under `vendor/drupal/` instead of `drush/`. In my case this is configured via _composer/installers_ install paths - _vendor/drupal_ for type _drupal-core_, _drush/{$name}_ for type _drupal-drush_:

```
"extra": {
  "installer-paths": {
    "vendor/drupal": [
      "type:drupal-core"
    ],

    // ...

    "drush/{$name}": [
      "type:drupal-drush"
    ],
  }
},
```

I checked your patch in the module's issue queue and project type seems to be correct there (_drupal-drush_), but any chance there's a discrepancy between that and the type value that the registry maintains?

**Comment by webflo** [comment]
Took me a while to understand the issue. The older releases of registry_rebuild are list on drupal packagist but as type library because these releases have no composer.json (https://packagist.drupal-composer.org/packages/drupal/registry_rebuild.json)

Please use the dev release (`composer require drupal/registry_rebuild:7.2.x-dev`) instead, this contains the committed composer.json from today.
