### ISSUE TITLE
Suggested require statement incorrect for dev branches

### ISSUE THREAD

**Issue by bradjones1** [drupal-composer/drupal-packagist#43]
The suggested require statement for dev branches is incorrect, as in, it doesn't pull in the expected branch in composer. Using the composer branch patterned-name (dev-branchname), as in the headline above, does.

![dev](https://cloud.githubusercontent.com/assets/981966/11454303/58aa5636-95e4-11e5-87e2-bfb03c433aa4.png)

**Comment by webflo** [comment]
Do you what happened instead?

**Comment by grasmash** [comment]
I ran into this same issue with the lightning package. The suggested require statement for `8.1.x-dev` is `"drupal/lightning": "8.1.*@dev"`, but that pulls in the latest beta tag `8.1.0-beta2` rather than the dev branch. 

If I use `"drupal/lightning": "8.1.x-dev"` in composer.json instead, it pulls in the latest commit from the dev branch.

**Comment by webflo** [comment]
I think you have `"prefer-stable": true` enabled in your composer.json? https://getcomposer.org/doc/04-schema.md#prefer-stable

**Comment by bradjones1** [comment]
Yes, though also, `"minimum-stability": "dev"`.

**Comment by webflo** [comment]
The behaviour of composer changes depending on these two settings. I can't change it, composers documentation is clear about how it works.

**Comment by grasmash** [comment]
From composer documentation: "If you require a dev version or only alphas are available for a package, those will still be selected granted that the minimum-stability allows for it."

It seems that using `"minimum-stability": "dev"` with `"prefer-stable": true` should still result in downloading the dev version, but it does not when using `"8.1.*@dev"`. It does when using `8.1.x-dev`. So, it seems that the example require statement on drupal-packagist should indicate `8.1.x-dev` as the version.

**Comment by webflo** [comment]
The new layout does not have the confusing require example anymore.
