### ISSUE TITLE
Composer won't install drupal/disqus

### ISSUE THREAD

**Issue by dustinleblanc** [drupal-composer/drupal-packagist#46]
Ran into this while trying to require the disqus module in my composer.json:

https://packagist.drupal-composer.org/packages/drupal/disqus

The dependencies on drupal/core and drupal/field here are somehow not satisfied by Drupal 8.0.2

I solved this by cloning the disqus module from d.o, adding my own composer.json details, and pushing my own fork to github and requiring that fork instead.

It seems that perhaps drupal-packagist is adding dependencies that may not be needed as I am happily now using the project without them. Not sure but thought it prudent to report so I can stop using my own fork.

**Comment by webflo** [comment]
Could you post your composer.json? Thanks!

**Comment by webflo** [comment]
Closed due to inactivity.
