### ISSUE TITLE
Panels 8.x-dev missing?

### ISSUE THREAD

**Issue by grasmash** [drupal-composer/drupal-packagist#47]
I've added to following dependency to my composer.json file:

```
"drupal/panels": "8.3.x-dev"
```

An received the following error: `The requested package drupal/panels could not be found in any version, there may be a typo in the package name.`.

Upon [searching Drupal packagist](https://packagist.drupal-composer.org/packages/drupal/panels) I found that it does not have an 8.x dev version of Panels listed, despite there [being on Drupal.org](https://www.drupal.org/project/panels). But, I think i've got got bigger problems than that, no version of Panels is recognized at all! E.g., using the following also fails:

```
"drupal/panels": "8.3.0-alpha20"
```

Note that `"minimum-stability": "dev"` is set, so I don't think that's the issue.

Assuming this is a bug?

**Comment by webflo** [comment]
Found a bug in drupal/parse-composer lib. Fixed it in 31abf39 and deployed it to production.
