### ISSUE TITLE
Drush version of extensions may be too restrictive

### ISSUE THREAD

**Issue by webflo** [drupal-composer/drupal-packagist#5]
_From @derhasi on January 13, 2015 8:32_

When I look at [registry_rebuild](http://drupal-packagist.webflo.io/packages/drupal/registry_rebuild) and [drush_language](http://drupal-packagist.webflo.io/packages/drupal/drush_language), the version constraint for those extensions seem to be too restrictive, as this will not allow to have drush 7 (dev-master) fulfill the requirement.

_Copied from original issue: webflo/packagist#10_

**Comment by webflo** [comment]
The version constraints are correct but you need https://packagist.org/packages/drush/drush instead of the drush package definitions from our drupal-packagist. But drupal-packagist has a higher priority than packagist.org

**Comment by webflo** [comment]
Always require "drush/drush" instead of "drupal/drush"

**Comment by webflo** [comment]
_From @derhasi on January 13, 2015 11:10_

I know "drush/drush", but the given version constraint is too restrictive:  `drush/drush: 6.*` and that does not allow to install `dev-master`or `7.*`.

**Comment by webflo** [comment]
_From @derhasi on January 13, 2015 11:12_

Where is that drush version comming from. I cannot find code for that.

**Comment by webflo** [comment]
_From @derhasi on January 21, 2015 8:50_

For reference: the drush version is set in https://github.com/drupal-composer/drupal-parse-composer/blob/58ebd43f71f1f23bb96052fa0f95e2d6cfc09273/src/Project.php#L108

**Comment by webflo** [comment]
We need different drush versions depending on the core version.

**Comment by greg-1-anderson** [comment]
I ran into this problem today. It would be good if Drush extensions were flagged to work with Drush 6 or later.

**Comment by greg-1-anderson** [comment]
I just added [8264eb](https://github.com/drush-ops/drush/commit/8264eb39f0574d1660191d4ffde1f49d76d326dc) so that Drush dev-master will match composer version ranges.

**Comment by greg-1-anderson** [comment]
c.f. PR above to change this.

**Comment by webflo** [comment]
Fixed by #21
