### ISSUE TITLE
How to avoid creating .git directories when adding dev versions as dependencies?

### ISSUE THREAD

**Issue by ptmkenny** [drupal-composer/drupal-packagist#50]
Hey, I just started using Drupal Packagist today and it's awesome.  I was able to get all the dependencies of my site into composer.json (https://drupal.stackexchange.com/questions/181754/how-to-use-composer-for-module-dependency/191589#191589), but when I run `composer update`, I notice that for any module that specifies a dev version, it clones it and leaves a `.git` directory.

I'm using Pantheon to host my site, so I need to commit the modules downloaded by composer and then push them to Pantheon-- but Pantheon complains about the dev versions of modules having `.git` directories.  Is there a way to configure composer.json so that the `.git` directories aren't created?  If not, do you have any suggestions for handling this (automatically removing the .git directories)?

**Comment by derhasi** [comment]
In our projects we use [a custom build.sh](https://gist.github.com/derhasi/57fbfc67fd2cd95f6b17) for that. We might replace that with a call to [composer archive](https://getcomposer.org/doc/04-schema.md#archive) and/or phing in the future.

**Comment by ptmkenny** [comment]
Ok, thanks.  I tried calling composer archive like this but the .git directories still appear:

```

  "archive": {
    "exclude": ["/.git", ".git", "/*.git", "/modules/*/.git"]
  },
```

So, instead, I added the .git directories to the gitignore: 

`/modules/*/.git`
