### ISSUE TITLE
Update dist packages to https

### ISSUE THREAD

**Issue by albertvolkman** [drupal-composer/drupal-packagist#51]
With this update-

https://github.com/composer/composer/issues/4968

Composer installs are now failing for me with-

> Failed to download drupal/<module> from dist: Your configuration does not allow connection to http://ftp.drupal.org. See https://getcomposer.org/doc/06-config.md#secure-http for details.

When doing a composer show <package>, it's showing that the dist packages are being served over http. I'm thinking the answer here is to update those links to utilize https?

**Comment by webflo** [comment]
The error message looks suspicious. `Failed to download drupal/ from dist`. "drupal/" is not a valid package name.

I updated all URLs to https a few weeks ago. Have you found some packages that are still http?

**Comment by albertvolkman** [comment]
Ah, sorry, Github apparently stripped out the <>'s. This example was admin_menu.

**Comment by webflo** [comment]
All URLs in Drupal Packagist are HTTPS. I think your lockfile contains old urls. Try to replace http with https.

I tired "composer show drupal/admin_menu 7.3.0-rc1" as example.

**Comment by albertvolkman** [comment]
My apologies... earlier I had deleted my composer.lock file and re-generated, but it was failing... but I think that was related to git.drupal.org being down. Thanks & closing.

**Comment by michaelrkn** [comment]
When I run:

``` shell
$ composer create-project drupal/drupal my_site_name
```

I get:

``` shell
Installing drupal/drupal (8.0.5)
  - Installing drupal/drupal (8.0.5)
    Cloning b35d70c688463fb3722c9ea4918f61033da37a4a


  [Composer\Downloader\TransportException]                                     
  Your configuration does not allow connection to http://git.drupal.org/proje  
  ct/drupal.git. See https://getcomposer.org/doc/06-config.md#secure-http for  
   details.
```

I tried `composer clear-cache` but that doesn't seem to help. Is there something that still needs to be moved to https, or am I missing something?

**Comment by webflo** [comment]
Hi, this is a known issue. You can track it on drupal.org https://www.drupal.org/node/2689133. I personally don't have access to this Package on Packagist and can't the git url. You can disable this new security feature via the secure-http option. https://getcomposer.org/doc/06-config.md#secure-http
