### ISSUE TITLE
No releases available for drupal/metatag.

### ISSUE THREAD

**Issue by bangpound** [drupal-composer/drupal-packagist#53]
Only alpha and beta versions of metatag module for Drupal 7 are advertised in Packagist, despite there being 13 proper releases of this module.
- https://www.drupal.org/project/metatag
- https://packagist.drupal-composer.org/packages/drupal/metatag

**Comment by sierkje** [comment]
I've running in that issue not just with metatag today, but also several other packages. Some have only alpha and beta releases listed, others do have full releases but not all of them. Here are a few other examples of packages that don't seem to have all releases available via packagist:
- https://packagist.drupal-composer.org/packages/drupal/libraries
- https://packagist.drupal-composer.org/packages/drupal/navbar
- https://packagist.drupal-composer.org/packages/drupal/redhen

**Comment by kplanz** [comment]
Just noticed some missing releases for panels and panels_everywhere:
- https://packagist.drupal-composer.org/packages/drupal/panels
- https://packagist.drupal-composer.org/packages/drupal/panels_everywhere

Those releases are from more than one year ago and I'm sure they were there before. So seems they did get lost at some point in the recent past.

**Comment by webflo** [comment]
Hi all, there was a hickup in the update process. I fixed the issue, the tags are currently rebuilding. Takes a while for all packages ...

**Comment by webflo** [comment]
E.g. redhen was updated a few minutes ago

**Comment by davidbarratt** [comment]
Thanks @webflo you're amazing!

**Comment by sierkje** [comment]
What davidbarratt said :)

**Comment by webflo** [comment]
Issue has been fixed.
