### ISSUE TITLE
Include drupal/drupal

### ISSUE THREAD

**Issue by bartfeenstra** [drupal-composer/drupal-packagist#57]
`drupal/drupal` is the entire Drupal core repository, which is not available on Drupal Packagist. The only available core package is `drupal/core`, which is everything from the Drupal core repository below `./core`. As we do not use `drupal-project` and want to use Drupal core's default front controller, we'd like to be able to depend on `drupal/drupal`.

Can the maintainers please include `drupal/drupal` in the list of available Drupal projects, either on Packagist itself or Drupal Packagist?

Let me know if there is anything I can do to help, or if I should provide more information.

Thanks a lot!

**Comment by davidbarratt** [comment]
@bartfeenstra,

It's on the main packagist. :)

https://packagist.org/packages/drupal/drupal
and
https://packagist.org/packages/drupal/core

**Comment by bartfeenstra** [comment]
Yeah I just realized that. There must be another reason why `composer install` did not find it.
