### ISSUE TITLE
drupal/drupal, drupal/core: Lets clean-up the mess

### ISSUE THREAD

**Issue by webflo** [drupal-composer/drupal-packagist#58]
`drupal/drupal` is on [Packagist](https://packagist.org/packages/drupal/drupal) and [Drupal Packagist](https://packagist.drupal-composer.org/packages/drupal/drupal). Both sites have a different understanding of this package, because Drupal Packgist does the automatic parsing of Info Files (and YAML).

Both sites are used in conjuction most of the time. Composer merges the package defintions from both sites.
- Keep 7.\* verions of drupal/drupal on Drupal Packagist, the 7.x branch has no composer.json. We need Drupal Packagist to generate one. People need drupal/drupal for their existing D7 workflows.
- Remove 8.\* versions of drupal/drupal from Drupal Packagist, the 8.x branches have a composer.json and Packagist handles it just fine.
- Open an issue on drupal.org infrastructure to setup a webhook for `drupal/drupal` on Packagist.
- Keep `drupal/core` as in on Packagist. `drupal/core` is a valid composer package. Its not necessary to mirror it on Drupal Packagist.

**Comment by bartfeenstra** [comment]
What causes the `drupal/drupal` discrepancy between the two sites in the first place? There should be no additional requirements other than those in `drupal/drupal`'s `composer.json`', do they? Why does Drupal Packagist not provide recent releases, when Packagist does?

**Comment by webflo** [comment]
Fixed the drupal/drupal package. https://packagist.drupal-composer.org/packages/drupal/drupal
