### ISSUE TITLE
Deprecation premature?

### ISSUE THREAD

**Issue by greg-1-anderson** [drupal-composer/drupal-packagist#61]
Of course it is a great idea to transition to the official repositories as soon as possible, but https://www.drupal.org/node/2718229 still recommends against use in production, and it seems that Drupal 7 does not work at all at the moment.  There is no schedule on the main node for when this will be supported, but perhaps that exists elsewhere.

In any event, perhaps it might be better to soften the deprecation warning on packagist.drupal-composer.org, and not set a hard end date until it is known when the drupal.org service will have a stable release.

**Comment by webflo** [comment]
I think its nothing wrong with deprecation itself. People should be aware that it will change in the future and January 2017 is plenty of time adapt. No? 

The deprecation changes nothing until January 2017, Drupal-Packagist will receive updates for all modules and themes until then.

**Comment by m4olivei** [comment]
Sharing my experience: It's a bit strong and confusing as it is. Yesterday when I was setting things up I started with Drupal Packagist, then saw the deprecation notice, so switched to https://packages.drupal.org/8 for future proofing. Then @greg-1-anderson pointed out that https://packages.drupal.org/8 is in alpha, so I switched back. As an end user, all I want to know which is the best to use now, which appears to be Drupal Packagist. I'd suggest changing the deprecation language to be less strong and somehow communicate that it's Drupal Packagist is totally here for you.  As it is you read "Drupal Packagist is deprecated, you should use the official Package Repository from Drupal.org instead.", and your like, OK, must do now.

**Comment by greg-1-anderson** [comment]
I agree that there is nothing wrong with making folks aware that there is an EOL coming for drupal-composer; however, "deprecate" means "strongly discourage", which is a recommendation not to use. As @m4olivei said, packages.drupal.org is not ready for production use yet; we should therefore be encouraging folks to use drupal-composer for now, while making them aware that this is a temporary solution and change will be required in the future.

It is unclear whether January 2017 is enough time to adapt or not.  If packages.drupal.org is production-ready next month, then yes. If it isn't production-ready until December, or February next year, then it isn't. I think we should wait until there is at least an announced date for packages.drupal.org before picking when drupal-composer will stop getting updates. While announced dates can always be changed, the current situation of having an EOL date for drupal-composer, but no launch date for packages.drupal.org will communicate to some "don't use composer for Drupal projects".

**Comment by bartfeenstra** [comment]
Software is generally deprecated when a better alternative is available, which will eventually replace the deprecated functionality entirely. That better alternative is not yet available in my opinion. There is an alternative, but it is in alpha, and the maintainers discourage anyone from relying on it.

For now, I would replace the deprecation warning with an informative notice that tells people to experiment with the drupal.org Packagist instead, because Drupal Packagist will become deprecated in the near future. This would prevent reactions of confusion such as @m4olivei's and general disappointment.

**Comment by ModulesUnraveled** [comment]
Totally agree. We had an internal discussion on Slack that went something like this:

> "Hey look! We're not supposed to use Drupal Packagist anymore. The new standard is packages.drupal.org."
> 
> "Oh, things don't work there yet."
> 
> "Oh, hey look, drupal.org says 'We strongly recommend against using Drupal.org's composer integration'."
> 
> "...Uh... so what are we supposed to use then..."
> 
> "It looks like drupal.org isn't supported yet, and the maintainers of Drupal Packagist don't want to support that anymore either..."
> 
> "yeah… conflicting information"
> 
> "use nothing?"
> 
> ![](http://i.kinja-img.com/gawker-media/image/upload/19by6na0fro2fgif.gif)

I'm sure we're not the only ones to be confused, so I'm in favor of a less harsh "deprecated" notice. Maybe instead of saying it is already deprecated, it should say something like

> Drupal Packagist is scheduled to be deprecated in January 2017 (or when packages.drupal.org is ready). Until then Drupal Packagist will continue to receive updates for all modules and themes.

**Comment by webflo** [comment]
Alright, i will change it in a few hours.

**Comment by ryanaslett** [comment]
I just wanted to chime in here that I think we're real close to being able to throw the beta switch. I dont think there are any more package naming changes, or version format changes left to be had.  I would encourage all of you to clear your composer cache and kick the tires so we can reveal any outstanding inconsistencies.  Essentially I'd like to give it another week, and call beta it then (July 6th?), (unless we find additional showstoppers).

**Comment by ryanaslett** [comment]
We did end up throwing the beta switch. We've only seen a couple of small bugs afterwards.
