### ISSUE TITLE
How often do Packagist.drupal-composer.org update git from drupal.org

### ISSUE THREAD

**Issue by cks3443** [drupal-composer/drupal-packagist#62]
We made tag 8.x-4.x-alpha1~4 as you look at the site below

http://cgit.drupalcode.org/varbase/refs/?h=8.x-4.x

but "packagist.drupal-composer.org" don't update tags from git
Now the site just have lists of tag was named in the past.

https://packagist.drupal-composer.org/packages/drupal/varbase

How often do "packagist.drupal-composer.org" update git from drupal.org ?

**Comment by webflo** [comment]
Hi, the composer.json in the repository is invalid. Please check every version constraint and run `composer validate`. The package should show up once this is fixed.

**Comment by cks3443** [comment]
We are using same composer.json with old tag (7.3.0-beta1). packagist.drupal updated old tag but now no ...

**Comment by derhasi** [comment]
Your composer package name has to follow the Drupal standards for drupal.org. Currently it is `vardot/varbase`, it should be `drupal/varbase`. See https://www.drupal.org/node/2471927

**Comment by webflo** [comment]
Resolved https://packagist.drupal-composer.org/packages/drupal/varbase#dev-8.x-4.x

**Comment by cks3443** [comment]
I thanks you for all
2016. 6. 30. 오후 5:55에 "Florian Weber" notifications@github.com님이 작성:
