### ISSUE TITLE
Drupal Packagist doesn't respect specific version constraints

### ISSUE THREAD

**Issue by balsama** [drupal-composer/drupal-packagist#63]
It seems that if a package specifies a specific version of a dependency, packagist will automatically add the tilde operator. For example, [drupal/lightning 1.02 specifically requires version 8.1.0 of drupal/views_infinite_scroll](https://github.com/acquia/lightning/blob/04b967e8b8fa6d65710faeb4ca2b8d3914b947cf/composer.json#L144). But [packagist is adding the tilde operator to it](https://packagist.drupal-composer.org/packages/drupal/lightning).

In this case, we specifically need 8.1.0 because we apply a patch to views_infinite_scroll (we have [a flowchart that dictates how we constrain versions](http://lightning.acquia.com/blog/dependency-version-contraints)).

The issue is causing downstream projects to fail because their environment fails when patches don't apply.

Any idea of why packagist is adding the tilde? Any chance we could get that changed?

**Comment by grasmash** [comment]
@webflo If you can point out the relevant area of code that might do this, I'd be happy to submit a PR.

**Comment by briantully** [comment]
indeed, it seems any entry in composer.json that is pegged at a specific version, e.g., "8.1.0" somehow gets processed as "~8.1.0". The workaround in drupal/lightning for 1.03 seems to be prefixing with a caret "^8.1.0" which gets respected when processed by drupal-packagist. However this is not ideal, as this only matches "non-breaking" versions. I've been digging through the drupal-packagist code and I don't see where it is parsing/processing composer.json files/requests. Any help on where to narrow my search and I too would offer up a PR.

**Comment by phenaproxima** [comment]
Spoke to @webflo about and he pinpointed it to drupal-composer/drupal-parse-composer@d7a0078. It's not entirely clear why it's imposing a relaxed version constraint, so we'll see if we can't get this fixed over there.

**Comment by balsama** [comment]
This was fixed in https://github.com/drupal-composer/drupal-parse-composer/issues/56. Confirmed that the original issue (views_infinite_scroll in lightning 1.02 wasn't pinned) is now fixed. Thanks!
