### ISSUE TITLE
8.x release missing for drupal/slack.

### ISSUE THREAD

**Issue by hussainweb** [drupal-composer/drupal-packagist#65]
The Drupal packagist only lists 7.x versions of slack module - https://packagist.drupal-composer.org/packages/drupal/slack. However, there is an 8.x release as we can see here - https://www.drupal.org/project/slack.

I am not sure if the composer.json in the module causes a problem but it appears valid.

I tried to find a generic issue for this but the closest I could find was #53. Should this be manually refreshed?

Sidenote: The package drupal/slack does not even come up in search. I have to manually type it in the URL to go to the page.

**Comment by webflo** [comment]
The composer.json of the slack module is invalid. Verify via

```
git clone --branch 8.x-1.x https://git.drupal.org/project/slack.git
cd slack
composer validate
```

```
 [Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 12:
  ...ode.org/slack"  },}
  --------------------^
  Expected: 'STRING' - It appears you have an extra trailing comma
```

**Comment by hussainweb** [comment]
Oh, I wish it worked on an invalid composer.json file. I am now stuck until my patch goes through, unless I add a special repository for this. Will that work?

**Comment by webflo** [comment]
Yes, you can add your own fork to your composer.json and require it.
