### ISSUE TITLE
No 7.x versions for drupal/redis and drupal/feeds

### ISSUE THREAD

**Issue by pbuyle** [drupal-composer/drupal-packagist#67]
It used to work a few days ago, but as of today there is 7.x version of [drupal/redis](https://packagist.drupal-composer.org/packages/drupal/redis). Off course, there is a 7.x release on drupal.org.

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package drupal/redis ^7.3 exists as drupal/redis[8.1.0-alpha1, dev-8.x-1.x, 8.1.x-dev] but these are rejected by your constraint.
```

**Comment by pbuyle** [comment]
Same issue for [drupal/feeds](https://packagist.drupal-composer.org/packages/drupal/feeds).

**Comment by webflo** [comment]
Sorry, don't know what happened exactly. Triggered an update on for both module.

**Comment by pbuyle** [comment]
Thanks
