### ISSUE TITLE
No 8.x-3.0-alpha1 package for LDAP module

### ISSUE THREAD

**Issue by timwood** [drupal-composer/drupal-packagist#68]
Just noticed the 8.x-3.0-alpha1 release of the [LDAP module](https://www.drupal.org/project/ldap) from Aug. 5 isn't available on Drupal Packagist. Yet the 8.x-3.x-dev is. Is there anything we can do to fix this? Does packagist have a policy of not publishing packages for D.O. alpha releases?

Thanks!

**Comment by webflo** [comment]
Drupal Packagist won't receive any bugfix anymore. Sorry. 8.3.0-alpha2 and 8.3.0-alpha3 is available. This should mitigate the problem.
