### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by jcnventura** [drupal-composer/drupal-packagist#69]
After #61, the deprecation warning became "Drupal Packagist is scheduled to be deprecated in January 2017 (or when the official Package Repository from Drupal.org is ready). Until then Drupal Packagist will continue to receive updates for all modules and themes."

The official package repo is now been marked ready (https://www.drupal.org/drupalorg/blog/drupalorgs-composer-endpoints-are-out-of-beta), and it's January 2017.

Some of our projects are still using this packagist, and others in the same situation might be interested in a more precise deadline of the date when it stops synchronizing module info with drupal.org.

**Comment by webflo** [comment]
Good idea, we have a open PR for it. https://github.com/drupal-composer/drupal-packagist/pull/60

I will deploy it this week.
