### ISSUE TITLE
http://packagist.drupal-composer.org is dead

### ISSUE THREAD

**Issue by SiliconMind** [drupal-composer/drupal-packagist#70]
Just so everyone that tries to use http://packagist.drupal-composer.org is aware that it has been replaced by packages.drupal.org and you need to update your `composer.json` file as described on [drupal.org](https://www.drupal.org/docs/develop/using-composer/using-packagesdrupalorg).

`drupal-packagist` project on GitHub should be updated so that people no longer will try to use http://packagist.drupal-composer.org

**Comment by webflo** [comment]
Done, i published the deprecation notice for the repo.
